ev-dev-tools/setup.cfg
ev-dev-tools/src/ev_cli/ev.py
ev-dev-tools/src/ev_cli/templates/helper_macros.j2
ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2
ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2
ev-dev-tools/src/ev_cli/templates/interface-Impl.cpp.j2
ev-dev-tools/src/ev_cli/templates/interface-Impl.hpp.j2
ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2
ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2
ev-dev-tools/src/ev_cli/templates/module.cpp.j2
ev-dev-tools/src/ev_cli/templates/module.hpp.j2

- the year tags are not included in auto-generated files, that might be
overwritten again in future because the regexp and file handling would
introduce quite some complexity, which might not be worth it
- only for implementation files, that will never be touched again by the
generator (except forced overwrite), the current year is included and
can be updated by the user

Including SPDX license headers in generated files

---

ev-dev-tools/setup.cfg
ev-dev-tools/src/ev_cli/ev.py
ev-dev-tools/src/ev_cli/helpers.py

- ev-cli will now use clang-format by default
- it will use the .clang-format file in the current working directory by
default
- to explicitly disable clang-format, the --disable-clang-format flag
was added

Enable clang-format by default

---

docker/everest-playground-ubuntu-20-04/Dockerfile
docker/everest-playground/Dockerfile
ev-dev-tools/setup.cfg
ev-dev-tools/src/ev_cli/ev.py
ev-dev-tools/src/ev_cli/templates/CMakeLists.txt.j2

- ld-ev will now be generated by 'ev-cli module generate-loader' into a
separate directory, to play well with the new way of building the
loader
- adjusted CMakeLists.txt template to reflect these changes

Added separate handling of ld-ev

---

ev-dev-tools/src/ev_cli/__init__.py
ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2
ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2

This allows a module to inquire the (locally) unique module id of its requirements.

Add "module_id" from requirements connection to Interface

---

ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2

This allows to call publish functions directly from module code. In the
current implementation this is only possible by using a sigslot signal
in the mod code and subscribing to that in the implementation code with
a publish wrapper which adds quite some unneccesary code.
Signed-off-by: Cornelius Claussen <cc@pionix.de>

Change var publish access from protected to public

---

ev-dev-tools/src/ev_cli/templates/types.hpp.j2

We stumbled over the problem that we cannot pass types directly to EVLOG_*. According to:
https://stackoverflow.com/questions/74451640/overloading-ostream-operator-works-for-stdcout-but-not-for-boostlog
Quote:
Your operator<< must be able to be found using ADL from Boost.Log namespace. For this, the operator must be defined in the namespace of one of its argument types.
So let's move the generated operator a few line highe into the namespace.

Move generated operator<< for types into namespace

---

docker/docker-compose.yml
docker/steve/Dockerfile

Starting up a `steve`-container and `mariadb`  with a new, clean volume `ocpp-db-data` results in this error:
> [ERROR] Migration of schema `ocpp-db` to version "0.7.7 - update" failed! Please restore backups and roll back database and code!
<details><summary>Details</summary>
<p>
> [ERROR] Migration of schema `ocpp-db` to version "0.7.7 - update" failed! Please restore backups and roll back database and code!
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  18.849 s
> [INFO] Finished at: 2023-11-02T12:59:23Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal …

update `mariadb`-version to fix SteVe schema-migration failure; update SteVe to latest version

---

everest-testing/src/everest/testing/ocpp_utils/charge_point_v201.py

The handler is needed for testing use case M06 - Get V2G Charging Station Certificate status

tests: add handler for Action.GetCertificateStatus to ChargePoint201

---

ev-dev-tools/src/ev_cli/helpers.py
ev-dev-tools/src/ev_cli/type_parsing.py

Currently we may include (and often do) the header we generate also in the include list - this pr removes the current header file from the derived include list

Fix self include for the generated type headers

---

everest-testing/src/everest/testing/core_utils/configuration/libocpp_configuration_helper.py

Adjust network configuration to recent changes in libocpp which now uses the SecurityCtrl Identity as postfix for the CSMS url; also does not per default set the right protocol any more.

Adjust network configuration to recent changes in libocpp

---

everest-testing/src/everest/testing/core_utils/probe_module.py

NOTE: This may not be a full fix, as asyncio objects technically aren't thread-safe, but it works well enough for now.

fix: Probe module waits for ready signal in another thread to avoid hangs

---

docker/everest-docker-image/Dockerfile

install libcap2 instead of libcap

Fix typo in Dockerfile

---

.github/workflows/deploy-all-docker-images.yml
.github/workflows/deploy-single-docker-image.yml
docker/everest-clang-format/Dockerfile
docker/everest-clang-format/run-clang-format.py

* Use clang-format version 15.0.6
* Use clang-format from package manager
* Move run-clang-format script to everest-utils
related to https://github.com/EVerest/everest-ci/issues/11#issuecomment-1863029492

Fix "clang-format version 16.0.0"-bug

---

everest-testing/src/everest/testing/core_utils/controller/everest_test_controller.py
everest-testing/src/everest/testing/core_utils/controller/test_controller_interface.py

replace rcd_error with diode_fail to produce faulted state in OCPP

Replace RCD error with diode_fault

---

BUILD.bazel
ev-dev-tools/BUILD.bazel
everest-testing/BUILD.bazel
third-party/bazel/BUILD.bazel

Here we move the formatting checks to the root build file, that is not supposed to be consumed by the downstream repositories.
This way they don't need to add all the dependencies for formatting in the downstream repositories.

Bazel: Move formatting tests to the root

---

ev-dev-tools/src/ev_cli/__init__.py
ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2
ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2
ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2
ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2

Implementation Base Template:
* Add error_manager
* Add error_state_monitor
* Add error_factory
* Update raise_error interface
* Update clear_error interface
Export Template
* Add error_manager
* Add error_state_monitor
* Update subscribe_error interface
ld-ev template
* Update subscribe_global_all_errors interface
* Should be merged together with https://github.com/EVerest/everest-framework/pull/186

Refactor error framework C++ interface 

---

everest-testing/setup.cfg
everest-testing/src/everest/testing/core_utils/everest_core.py

Some packages used in everest-testing have newer versions that cause conflicts. The working version of the dependency is now explicitly listed

fix: Python testing dependnecies

---

CMakeLists.txt
ev-dev-tools/CMakeLists.txt
everest-testing/CMakeLists.txt

Add `CMakeLists.txt` files to allow pip install targets and weel build targets for  `ev-dev-tools` and `everest-testing`
* https://github.com/EVerest/everest-cmake/pull/4

Add CMake to python packages ev-dev-tools and everest-testing

---

ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2

Without this attribute, interfaces without commands generate a lot of warnings since the parameter is not used inside the function.

ev_cli: attribute parameter of _gather_cmds with [[maybe_unused]]

---

ev-dev-tools/src/ev_cli/__init__.py
ev-dev-tools/src/ev_cli/ev.py

This was accidentally set to 'update-if-non-existent' which prevents the ld-ev files to be re-generated if they already exist but something in the module manifest has changed

ev-cli: Fix update of ld-ev files

---

ev-dev-tools/setup.cfg
ev-dev-tools/src/ev_cli/__init__.py
ev-dev-tools/src/ev_cli/licenses/spdx.org/licenses/Apache-2.0
ev-dev-tools/src/ev_cli/licenses/spdx.org/licenses/Apache-2.0.html

Otherwise a globally installed ev-dev-tools/ev-cli will not be able to find this licenses directory
Add additional aliases for Apache-2.0 license used in EVerest modules

ev-cli: fix: install missing licenses directory

---

ev-dev-tools/src/ev_cli/__init__.py
ev-dev-tools/src/ev_cli/templates/types.hpp.j2

Add the comparison operator `==` and the explicit opposite `!=` to all generated complex types.
Also improve the formatting of the generated types' code regarding indentation, whitespace and line lengths, for "readability". (I am aware that this code isn't often read. We often look things up from the reference within the code editor though.) Other code, such as the interface implementations, still has wild formatting.
The YAML types generation is being used by the coming JSON RPC API module **RpcApi** ([WIP branch](https://github.com/EVerest/everest-core/tree/feature/json-rpc-api)), because of its ease of creating complex C++ object/struct trees with optional members. A comparison operator is a massive relief for checking for changes e,g, after applying setters.
---
This is an example of …

Generated types: introduce comparison operators

---

ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2

Fix typo in code generator template generating subscriptions

---

everest-testing/src/everest/testing/ocpp_utils/central_system.py

This can contain a list of Actions that have validation turned off
For example you can do the following: skip_validation.append(Action.boot_notification) to turn off validation during BootNotification responses

Add skip_validation list to allow non-validated responses

---

ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2

Removed staging namespace from import because it has been removed in everest-core

Remove staging from jinja
