ev-dev-tools/setup.cfg, ev-dev-tools/src/ev_cli/helpers.py, ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2, ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2, ev-dev-tools/src/ev_cli/templates/module.hpp.j2
- also fixed --which option handling, the filter was not returning a
proper list
=> Added autogen support for ModuleInfo

ev-dev-tools/setup.cfg, ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/helpers.py, ev-dev-tools/src/ev_cli/templates/helper_macros.j2, ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2, ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2
- support for 'null' type handling in everest-framework
=> Fix 'null' type handling

ev-dev-tools/setup.cfg, ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2
The size of the whole connections vector was wrongly used for creating the subscription idxs.
This fix instead correctly uses the size of the connections["requirement_name"]
=> Fix requirement connections

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/templates/CMakeLists.txt.j2, ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2, ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2
=> Add support for building modules as binaries

docker/everest-playground-opensuse-tumbleweed/Dockerfile, docker/everest-playground-ubuntu-20-04/Dockerfile, docker/everest-playground/Dockerfile
=> Add missing libcurl development headers, needed for utc date changes

ev-dev-tools/setup.cfg, ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/helpers.py, ev-dev-tools/src/ev_cli/templates/helper_macros.j2, ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2, ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2, ev-dev-tools/src/ev_cli/templates/interface-Impl.cpp.j2, ev-dev-tools/src/ev_cli/templates/interface-Impl.hpp.j2, ev-dev-tools/src/ev_cli/templates/module.cpp.j2, ev-dev-tools/src/ev_cli/templates/types.hpp.j2, ev-dev-tools/src/ev_cli/type_parsing.py
Create enums and structs from inline type definitions, or from json files in a types folder.
=> Add complex type support

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/templates/types.hpp.j2
=> Fix enum handling for optional types

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/templates/CMakeLists.txt.j2
- update necessary libraries for modules
- remove install targets from cmakelists
=> Adapted changes for refactored cmake handling

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2
=> Fix enum publishing

.github/workflows/deploy-everest-ci-env.yml, docker/everest-ci-env/Dockerfile
Signed-off-by: Andreas Heinrich <andreas.heinrich@rwth-aachen.de>
=> Add ci environment docker and a deployment workflow

docker/everest-docu/.devcontainer/Dockerfile, docker/everest-docu/.devcontainer/devcontainer.json, docker/everest-docu/.gitignore, docker/everest-docu/Makefile, docker/everest-docu/readme.rst, docker/everest-docu/source/conf.py, docker/everest-docu/source/index.rst, docker/everest-docu/source/testpage.rst
=> Initial draft for a ReST documentation env

ev-dev-tools/src/ev_cli/helpers.py
=> Increase width for json2yaml conversion

ev-dev-tools/src/ev_cli/ev.py
=> Remove too restrictive checks

ev-dev-tools/src/ev_cli/__init__.py
=> Prevent version incompatibility

docker/everest-docker-image/.gitignore, docker/everest-docker-image/Dockerfile, docker/everest-docker-image/README.md, docker/everest-docker-image/build.sh, docker/everest-docker-image/logging.ini
You can build docker images of everest-core or out-of-tree repositories using the provided utility script
Signed-off-by: pietfried <piet.goempel@pionix.de>
=> Tooling for EVerest docker images

ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/templates/types.hpp.j2, ev-dev-tools/src/ev_cli/type_parsing.py
- this improves ccache performance and is just more consistent
=> Fix ordering of include files

everest-testing/README.md, everest-testing/examples/conf/everest-config-ocpp16.yaml, everest-testing/examples/conf/everest-config-ocpp201.yaml, everest-testing/examples/conf/ocpp16-config.json, everest-testing/examples/conftest.py, everest-testing/examples/tests.py, everest-testing/src/everest/testing/ocpp_utils/charge_point_utils.py, everest-testing/src/everest/testing/ocpp_utils/charge_point_v16.py, everest-testing/src/everest/testing/ocpp_utils/charge_point_v201.py
* fixed tests and pytest initialization
* fixed config paths
* improved wait_for_and_validate_function: It now can check for complete or subset of exp_payloads
=> Polish of everest-testing

.github/workflows/deploy-everest-ci-env.yml, docker/everest-clang-format/Dockerfile
=> Add clang-format docker

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/templates/interface-Exports.hpp.j2
@hikinggrass if you find it mandatory to bump the version, please do so
=> Changes for EVerest/everest-framework#110

ev-dev-tools/src/ev_cli/templates/types.hpp.j2
The currently generated type headers are not self-contained - added missing includes
=> Tempalte: fix missing includes

everest-testing/src/everest/testing/core_utils/fixtures.py
The PR introduces a new test fixture, `everest_config_visitors`, which returns the final list of `EverestConfigAdjustmentVisitor`s which will mutate the EVerest config for the test.
By introducing a new fixture, this allows tests to override it, allowing more flexibility in the use of config visitors - for example, it allows the overriding fixture to easily use test-local fixtures (e.g. temporary paths).
=> refactor: Make a separate fixture for the config visitors

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/ev.py, ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2, ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2
* Add subscribe_global_all_errors to ld-ev
* Add bool 'enable_global_errors' to template data
=> Add Feature: Subscribing to global all errros

docker/everest-docker-image/Dockerfile
Bugfix/add libcap dependency docker
=> Add libcap to Dockerfile

everest-testing/src/everest/testing/core_utils/_configuration/everest_configuration_strategies/ocpp_module_configuration_strategy.py, everest-testing/src/everest/testing/core_utils/_configuration/everest_environment_setup.py, everest-testing/src/everest/testing/core_utils/controller/everest_test_controller.py
* removed CertsPath from config that is not required anymore.
* Fixed id_token publish of everest_test_controller
=> Fixes for everest-testing

everest-testing/src/everest/testing/ocpp_utils/charge_point_utils.py
Fixes an issue when CALLERROR messages are validated.
Note: The validation of CALLERROR messages is currently not supprorted. This PR only fixes issues when CALLERROR messages are initiated by the charge point
=> handling CALLERROR in validation function

ev-dev-tools/src/ev_cli/__init__.py, ev-dev-tools/src/ev_cli/templates/ld-ev.cpp.j2, ev-dev-tools/src/ev_cli/templates/ld-ev.hpp.j2
=> Add `ErrorStateMonitor` for global errors

docker/everest-docker-image/configuration/ocpp/ocpp-config.json
=> Change variable NumberOfDisplayMessages to DisplayMessages

ev-dev-tools/src/ev_cli/templates/interface-Base.hpp.j2
Support was added by modifying the template file.
=> feat(vars): Support for an array of string enums
